### ISSUE TITLE
Corrupted vanilla 4.6.0 kernel with CONFIG_MNATIVE and gcc-5.3.0

### ISSUE THREAD

**Issue by bircoph** [graysky2/kernel_gcc_patch#15]
Hello,

I stumbled upon serious issue with vanilla 4.6.0 kernel and CONFIG_MNATIVE: I got random userspace application segfaults: under high CPU/memory pressure any app may segfault at seemingly random stack point (firefox, screen, emerge, gcc, whatever). Gcc version is 5.3.0, hardware is x86 Atom N270 (eeepc 1000H). Vanilla kernel on the same setup (hardware, compiler, kernel config all the same, but CPU optimization set to CONFIG_MATOM) works perfectly fine, physical memory is fine too (multiple rounds of memtest86+ are OK).

I have some plans to test this issue further (try different compiler, e.g. 4.9.3) and try CONFIG_MATOM using your patch. For now I don't know where the problem comes from: this can be gcc bug, kernel bug or patch bug. But problem is very serious – compiled kernel is (almost) unusable and bug is hard to trace (I spent several days for testing, because I suspected other kernel or system changes responsible for this issue). Kernel config is here: https://bpaste.net/show/4d35b6b07786

P.S. I use CONFIG_MNATIVE widely on another systems, but all of them have older kernels, built with older compilers.

**Comment by bircoph** [comment]
With gcc-4.9.3 and CONFIG_MNATIVE kernel-4.6.0 works fine. So problem is either in gcc-5.3.0 or triggered by it.

**Comment by graysky2** [comment]
I'm not sure what I can do if a particular version of gcc is to blame; as far as I know, the code is solid as-is.  Another complication here is that your specific hardware might be a variable too.  The experiment to rule out your hardware would be for someone else to run your kernel but that would require an Atom CPU.

I assume that you controlled for only changing the CPU type (ie all other kernel config options are left the same)?

**Comment by bircoph** [comment]
> I assume that you controlled for only changing the CPU type (ie all other kernel config options are left the same)?

Yes.

I tested one more configuration: 4.6.0 kernel, gcc-5.3.0 and CONFIG_MATOM – works fine. So it is -march=native that fires up. Maybe gcc bug, maybe kernel bug is being exposed.

But what about following: -march=native selects not only march and mtune, but also sets a lot of other options; on another side kernel is quite picky and disables many gcc flags (e.g. to avoid FP instructions). What if some of this native-induced flags is not filtered properly and breaks kernel?

On this host -march=native expands as follows:
`
 $ gcc -### -march=native /usr/include/stdio.h 2>&1 | grep march
COLLECT_GCC_OPTIONS='-march=native'
 /usr/libexec/gcc/i686-pc-linux-gnu/5.3.0/cc1 -quiet /usr/include/stdio.h "-march=bonnell" -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mno-cx16 -msahf -mmovbe -mno-aes -mno-sha -mno-pclmul -mno-popcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mno-avx -mno-avx2 -mno-sse4.2 -mno-sse4.1 -mno-lzcnt -mno-rtm -mno-hle -mno-rdrnd -mno-f16c -mno-fsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mno-xsave -mno-xsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx --param "l1-cache-size=24" --param "l1-cache-line-size=64" --param "l2-cache-size=512" "-mtune=bonnell" -quiet -dumpbase stdio.h -auxbase stdio -o /tmp/ccN08ZTN.s "--output-pch=/usr/include/stdio.h.gch"
`

Filtering this out of -mno-* gives the following list:
`
"-march=bonnell"
-mmmx
-msse
-msse2
-msse3
-mssse3
-msahf
-mmovbe
-mfxsr
--param "l1-cache-size=24"
--param "l1-cache-line-size=64"
--param "l2-cache-size=512"
"-mtune=bonnell"
`

sahf should be noop on 32-bit x86. movbe and fxsr may be a trouble, as well as l1-cache-size=24, since this CPU has separate L1 instruction and data caches with different sizes:

`
$ x86info -c
[snip]
Cache info
 L1 Instruction cache: 32KB, 8-way associative. 64 byte line size.
 L1 Data cache: 24KB, 6-way associative. 64 byte line size. ECC.
 L2 cache: 512KB, 8-way associative. 64 byte line size.
`

**Comment by Ferroin** [comment]
The other question is: Where does this go on the command line?  The kernel build disables auto-generation of SSE and MMX stuff, but if the -mtune=native ends up after the options to do that, it might override them, and the auto-vectorization code would definitely give you a kernel which can't run most userspace (because FPU registers are supposed to be preserved across syscalls, and with SSE and/or MMX involved on the kernel size, that may not always be the case).

As far as the cache size stuff, that will only hurt performance, not render the kernel unusable, and I think GCC only uses it for stuff like structure alignment, so I think that keying off of the D-cache is correct in this case (although having different sized I and D caches on something used in a general purpose computer is a bit odd).

**Comment by bircoph** [comment]
The order on the command line doesn't matter in this case: gcc gives precedence for explicitly provided options over -march=* expansion, try:

```
$ gcc -### -mno-mmx -mno-sse -march=native /usr/include/stdio.h 2>&1 | grep sse
COLLECT_GCC_OPTIONS='-mno-mmx' '-mno-sse' '-march=native'
 /usr/libexec/gcc/i686-pc-linux-gnu/5.3.0/cc1 -quiet /usr/include/stdio.h "-march=bonnell" -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mno-cx16 -msahf -mmovbe -mno-aes -mno-sha -mno-pclmul -mno-popcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mno-avx -mno-avx2 -mno-sse4.2 -mno-sse4.1 -mno-lzcnt -mno-rtm -mno-hle -mno-rdrnd -mno-f16c -mno-fsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mno-xsave -mno-xsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx --param "l1-cache-size=24" --param "l1-cache-line-size=64" --param "l2-cache-size=512" "-mtune=bonnell" -quiet -dumpbase stdio.h -mno-mmx -mno-sse -auxbase stdio -o /tmp/ccpkSaIM.s "--output-pch=/usr/include/stdio.h.gch"
```

Also I checked on a well tested system with over a year old kernel and CONFIG_MNATIVE: it insersts march after -mno-* arguments:

```
/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.3/gcc -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -m64 -mno-mmx -mno-sse -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -march=native -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fno-var-tracking-assignments -pg -mfentry -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -c -o crypto/ctr.o /root/.ccache/tmp/ctr.stdout.subaru.15406.U5MMOr.i
```

I have no segfaults there so far.

As for the I and D caches issue, I agree with you, this can only affect performance.

**Comment by bircoph** [comment]
Probably you could add a warning for users that with some kernels and compilers (e.g. 4.6.0 and 5.3.0) problems are possible with -march=native.

**Comment by voondo** [comment]
A cause of this trouble could be this pull: [x86/asm changes for v4.6](http://lkml.iu.edu/hypermail/linux/kernel/1603.1/04800.html) (a lot of asm rewritten in C)

**Comment by graysky2** [comment]
Just to be clear, this bug only affects gcc-4.9.3 building 4.6.x (and likely future kernels) using native on an Atom CPU?  @bircoph - can or can you confirm that other versions of gcc are unaffected building native on the same hardware?

**Comment by bircoph** [comment]
@graysky2 
> can or can you confirm that other versions of gcc are unaffected building native on the same hardware?

Yes, on the same hardware I have problems only with gcc-5.3.0 and kernel-4.6.0. gcc-4.9.3 is unaffected even with -march=native.

**Comment by bircoph** [comment]
> A cause of this trouble could be this pull: x86/asm changes for v4.6 (a lot of asm rewritten in C)

Right now I can't test this, Though in few weaks I might be able to test this theory if pointed patch can be reverted cleanly from current 4.6.x kernel.

**Comment by graysky2** [comment]
@bircoph - Can you comment.  Is this still an issue?

**Comment by bircoph** [comment]
Yes, it is, on the same hardware with vanilla kernel 4.8.6 and gcc 5.4.0: CONFIG_MNATIVE leads to random userspace segfaults while CONFIG_MATOM works fine.

Will test with gcc-6.2.0 and report back.

**Comment by bircoph** [comment]
Vanilla kernel 4.8.6 causes userspace segfaults with every gcc version I tested: 4.9.3, 5.4.0, 6.2.0. Though failure rate is different: 5.4 > 6.2 > 4.9.3.

Looks like gcc itself is not the reason here, since I was able to reproduce failure on 4.9 series.

For 4.8.6 kernel and gcc-5.4.0 I can disassemble both CONFIG_MNATIVE and CONFIG_MATOM kernel to see the difference. (I don't need to disasm modules since none of them were loaded during tests.) The problem is to analyse this data properly. It should be reasonable to look for any FP instructions sneaked in; though it is hard to construct full list of them, including FPU, SIMD and undocumented stuff.

Can someone point me to a sane way to spot FP instructions in asm code? Any other suggestion for objdump-based comparison and analysis?

**Comment by graysky2** [comment]
Interesting observation and it seems reproducible for you.  Just to summarize, it's the native option that causes the issues whereas the atom option is fine, yes?

**Comment by bircoph** [comment]
Yes, exactly.

**Comment by graysky2** [comment]
> Probably you could add a warning for users that with some kernels and compilers (e.g. 4.6.0 and 5.3.0) problems are possible with -march=native.

That's probably the best "solution" at this point then...

**Comment by graysky2** [comment]
I have removed the native option in my dev branch for this and other reasons.  See the discussion in #19 for example.
