### ISSUE TITLE
Piledriver and Steamroller #ELIF/#DEFINE out-of-order

### ISSUE THREAD

**Issue by mharder** [graysky2/kernel_gcc_patch#20]
The Piledriver and Steamroller #ELIF/#DEFINE statements are out of order.

If CONFIG_MPILEDRIVER is true, the patch sets up STEAMROLLER,
and visa-versa for CONFIG_MSTEAMROLLER.

+#elif defined CONFIG_MPILEDRIVER
+#define MODULE_PROC_FAMILY "STEAMROLLER "
+#elif defined CONFIG_MSTEAMROLLER
+#define MODULE_PROC_FAMILY "PILEDRIVER "

**Comment by graysky2** [comment]
Good catch, thanks.
