### ISSUE TITLE
Error applying to Kernel 4.13+

### ISSUE THREAD

**Issue by nimrud** [graysky2/kernel_gcc_patch#27]
Tried to patch on Kernel 4.13.2 (Arch Linux) and using the the 4.13+ gcc patch and I'm getting this error:

patch: **** Only garbage was found in the patch input.
==> ERROR: A failure occurred in prepare().

EDIT: Ops, my mistake: the .patch file was downloaded not right resulting in bad contents.

What the proper way of getting the patch (source in PKGBUILD)?

**Comment by sirlucjan** [comment]
For example:

_gcc_path="https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master"
_gcc_patch="enable_additional_cpu_optimizations_for_gcc_v4.9+_kernel_v4.13+.patch"

and

source=(....
             "${_gcc_path}/${_gcc_patch}"
             ....)
