### ISSUE TITLE
Intel Skylake X (skylake-avx512)

### ISSUE THREAD

**Issue by Maxqia** [graysky2/kernel_gcc_patch#32]
Can you add Skylake X to the lists?
It should be -march=skylake-avx512.

**Comment by graysky2** [comment]
Please try 
 https://github.com/graysky2/kernel_gcc_patch/commit/917031201badcdc603d70f6d9156572af4b4154d

**Comment by Maxqia** [comment]
Builds and runs, don't know how to test if it runs faster, but that's fine for me
