### ISSUE TITLE
4.13+ patch does not apply to 4.16

### ISSUE THREAD

**Issue by wschlich** [graysky2/kernel_gcc_patch#34]
applying enable_additional_cpu_optimizations_for_gcc_v4.9+_kernel_v4.13+.patch to 4.16:

PATCH COMMAND:  patch -p1 -g0 -E --no-backup-if-mismatch  --dry-run -f < '/local/portage/patches/sys-kernel/gentoo-sources/gentoo-sources.patch'

================================
checking file arch/x86/include/asm/module.h
Hunk #1 succeeded at 25 (offset 10 lines).
Hunk #2 succeeded at 61 (offset 10 lines).
checking file arch/x86/Kconfig.cpu
Hunk #1 succeeded at 116 (offset 1 line).
Hunk #2 succeeded at 149 (offset 1 line).
Hunk #3 succeeded at 158 (offset 1 line).
Hunk #4 succeeded at 166 (offset 1 line).
Hunk #5 succeeded at 324 (offset 1 line).
Hunk #6 succeeded at 334 (offset 1 line).
Hunk #7 succeeded at 354 (offset 1 line).
Hunk #8 succeeded at 435 (offset 1 line).
Hunk #9 succeeded at 472 (offset 1 line).
Hunk #10 FAILED at 502.
1 out of 10 hunks FAILED
checking file arch/x86/Makefile
Hunk #1 succeeded at 124 (offset 3 lines).
checking file arch/x86/Makefile_32.cpu
Hunk #1 succeeded at 23 (offset 1 line).
Hunk #2 succeeded at 43 (offset 1 line).

patch program exited with status 1
================================

**Comment by pfactum** [comment]
```
PATCH COMMAND: patch -p1 -g0 -E --no-backup-if-mismatch --dry-run -f < '/local/portage/patches/sys-kernel/gentoo-sources/gentoo-sources.patch'
```
Are you sure Gentoo patches are relevant here?

**Comment by wschlich** [comment]
Hmm, seemingly I wasn't :(
What made me believe I already did was the fact that the latest commit only updated references of the kernel version from 3.15 to 4.13 and the version I was using already contained the 4.13 references. Very weird. Thanks for the headsup!

**Comment by wschlich** [comment]
Also, this was a duplicate of #31
