### ISSUE TITLE
[Info] GCC -march=native patch posted on LKML

### ISSUE THREAD

**Issue by ghost** [graysky2/kernel_gcc_patch#37]
Recently there was patch posted on LKML which adds `-march=native` option and is much more advanced than those in repo. Maybe you can look at it and borrows some ideas.

https://marc.info/?l=linux-kernel&m=152814762232748&w=4

**Comment by graysky2** [comment]
Thanks for the link.  That's over my head.  Let's see what upstream thinks about it.

**Comment by Ferroin** [comment]
FWIW, similar patches have been posted in the past, and they've pretty universally been rejected (I know because I was one of the people who posted such patches).

**Comment by ms178** [comment]
Again this week, with a similar rejection: https://lkml.org/lkml/2019/2/21/1011
