### ISSUE TITLE
Rebase against 5.7

### ISSUE THREAD

**Issue by sirlucjan** [graysky2/kernel_gcc_patch#47]
Hi grasky,

Could you look at:

https://github.com/torvalds/linux/commit/62d0fd591db1f9dcf68fb963b3a94af085a6b166

Regards

**Comment by mssx86** [comment]
can confirm that applying the 5.5+ patch on 5.7-rc3 fails:
```sh
 $ [linux-5.7-rc3]: patch -p1 < ../
patching file arch/x86/include/asm/module.h
Hunk #1 FAILED at 27.
Hunk #2 FAILED at 45.
2 out of 2 hunks FAILED -- saving rejects to file arch/x86/include/asm/module.h.rej
patching file arch/x86/Kconfig.cpu
patching file arch/x86/Makefile
patching file arch/x86/Makefile_32.cpu
 $ [linux-5.7-rc3]:
```

here's [arch/x86/include/asm/module.h.rej](https://0x0.st/ijR9.rej).

**Comment by sirlucjan** [comment]
@graysky2 @mssx86 

Could you try:

https://github.com/graysky2/kernel_gcc_patch/commit/a8eebc8325e78b0b968fc16ca415874d668de499

**Comment by mssx86** [comment]
> a8eebc8

patch does apply and build, thanks.

**Comment by graysky2** [comment]
@sirlucjan - Nice job, can you please send me a PR.

**Comment by sirlucjan** [comment]
Hm... I can't send a PR - for an unspecified reason the "send" option is not shown. Could you just push my commit with git am?

**Comment by graysky2** [comment]
Possibly, I too could not get a PR generated.  WTF?

**Comment by sirlucjan** [comment]
Cool. Thanks.
