### ISSUE TITLE
patch fails partially on kernel Debian 5.5.17-1kali

### ISSUE THREAD

**Issue by g4njawizard** [graysky2/kernel_gcc_patch#49]
last kernel I've build with 5.4 worked well. This one seems to have some problems...

```

cat /proc/verison
Linux version 5.5.0-kali2-amd64 (devel@kali.org) (gcc version 9.3.0 (Debian 9.3.0-10)) #1 SMP Debian 5.5.17-1kali1 (2020-04-21)


# patch < enable_additional_cpu_optimizations_for_gcc_v9.1+_kernel_v5.5+.patch -p1
or_gcc_v9.1+_kernel_v5.5+.patch -p1
patching file arch/x86/include/asm/module.h
patching file arch/x86/Kconfig.cpu
Hunk #10 FAILED at 558.
1 out of 11 hunks FAILED -- saving rejects to file arch/x86/Kconfig.cpu.rej
patching file arch/x86/Makefile
patching file arch/x86/Makefile_32.cpu

After exiting menuconfig:

scripts/kconfig/mconf  Kconfig

WARNING: unmet direct dependencies detected for X86_P6_NOP
  Depends on [n]: X86_64 [=y] && (MCORE2 [=n] || MPENTIUM4 [=n] || MPSC [=n])
  Selected by [y]:
  - MBROADWELL [=y] && <choice>


*** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.
```

**Comment by graysky2** [comment]
I need more info.  Which kernel version are you trying to build?  Is it a debian-patched or vanilla?  Where can I get the source you're attempting to patch?

Applies cleanly to 5.5.19 (vanilla):
```
cd linux-5.5.19
% patch -Np1 -i ./enable_additional_cpu_optimizations_for_gcc_v9.1+_kernel_v5.5+.patch
patching file arch/x86/include/asm/module.h
patching file arch/x86/Kconfig.cpu
patching file arch/x86/Makefile
patching file arch/x86/Makefile_32.cpu
```

**Comment by g4njawizard** [comment]
I think u missed the part in the text I posted?
" #1 SMP Debian 5.5.17-1kali1 (2020-04-21)"
I automatically received this version via the official kali repo's 
Thats all info I can give u.

**Comment by graysky2** [comment]
I read that but thought it referred to the kernel version you were running, not the one you are trying to compile.  I was able to download the kali source you mentioned from this mirror: http://http.kali.org/kali/pool/main/l/linux/

I can confirm that my patch does not apply to it as you found and can only assume that Kali applies their own patches to the vanilla kernel which interferes with my patch.  I don't have the time to support patching into non-vanilla source.  Sorry.

**Comment by g4njawizard** [comment]
Thats really sad, because it worked with 5.4.19 though.
