### ISSUE TITLE
Cannot apply patch to kernel 5.6.x

### ISSUE THREAD

**Issue by fturco** [graysky2/kernel_gcc_patch#51]
I have Linux 5.6.14 and GCC 10.1.0, and I'm not sure which patch I should apply.
I tried with the following ones, but they both fail (for different reasons):
* `enable_additional_cpu_optimizations_for_gcc_v10.1+_kernel_v4.19-v5.4.patch`
* `enable_additional_cpu_optimizations_for_gcc_v10.1+_kernel_v5.7+.patch`

**Comment by sirlucjan** [comment]
Could you try:

https://github.com/sirlucjan/kernel-patches/blob/master/5.6/cpu-patches-v3-sep/0001-cpu-5.6-merge-graysky-s-patchset.patch

**Comment by sirlucjan** [comment]
@graysky2 

Please look at:

https://github.com/graysky2/kernel_gcc_patch/pull/52

**Comment by fturco** [comment]
@sirlucjan: your patch seems to work. Thank you!

**Comment by sirlucjan** [comment]
Great. I have sent out PR.

**Comment by graysky2** [comment]
Thanks guys for bringing this up and for patching it.  Will review and pull.

**Comment by graysky2** [comment]
https://github.com/graysky2/kernel_gcc_patch/commit/8bbb34adf44784d870ffd8066c25ddf02011d001
