### ISSUE TITLE
Rebase against 5.8

### ISSUE THREAD

**Issue by sirlucjan** [graysky2/kernel_gcc_patch#54]
Due to minor changes [1] introduced in 5.8-rc1 the current patch cannot apply correctly.

[1] https://github.com/torvalds/linux/commit/a7f7f6248d9740d710fd6bd190293fe5e16410ac

```
Applying patch 0001-cpu-5.8-merge-graysky-s-patchset.patch...
patching file arch/x86/Kconfig.cpu
Hunk #1 FAILED at 123.
Hunk #2 succeeded at 155 with fuzz 2.
Hunk #3 succeeded at 164 with fuzz 2.
Hunk #4 FAILED at 172.
Hunk #5 succeeded at 259 with fuzz 2.
Hunk #6 FAILED at 269.
Hunk #7 FAILED at 278.
4 out of 11 hunks FAILED -- saving rejects to file arch/x86/Kconfig.cpu.rej
patching file arch/x86/Makefile
patching file arch/x86/Makefile_32.cpu
patching file arch/x86/include/asm/vermagic.h
```
My proposal for a solution:

https://github.com/graysky2/kernel_gcc_patch/pull/53

**Comment by graysky2** [comment]
Nice catch, thank you.  Merged.  As an aside, any thoughts about this: https://github.com/xanmod/linux/issues/58

**Comment by iadegesso** [comment]
With stable 5.8.0-r1 kernel the list of processor types is the same as without the patch..

**Comment by graysky2** [comment]
@iadegesso - What?

**Comment by sirlucjan** [comment]
Serio? Gdzie Ty widzisz te wszystkie procesory?

https://github.com/torvalds/linux/blob/master/arch/x86/Kconfig.cpu

Maybe I'm the one who's blind and I don't see them there?

**Comment by sirlucjan** [comment]
Maybe I'm the one who's blind and I don't see them there?

https://github.com/torvalds/linux/blob/master/arch/x86/Kconfig.cpu

Maybe I'm the one who's blind and I don't see them there?

**Comment by sirlucjan** [comment]
Maybe I'm blind, but I don't see it:

https://github.com/torvalds/linux/blob/master/arch/x86/Kconfig.cpu

**Comment by iadegesso** [comment]
No I manually aplied the patch and all went fine... Thanks

Iade
