### ISSUE TITLE
kernel>=5.7 and above can fail with bdver{2,3,4}, workaround is --mno-tbm

### ISSUE THREAD

**Issue by maxbritov** [graysky2/kernel_gcc_patch#55]
Gentoo issue: https://bugs.gentoo.org/726660

GCC issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95671
closed as invalid due kernel's objtool issue

I use this as workaround:

```diff -Naur linux-5.7.1-gentoo/arch/x86/Makefile linux-5.7.1-gentoo-2/arch/x86/Makefile
--- linux-5.7.1-gentoo/arch/x86/Makefile	2020-06-14 13:35:08.438907762 +0300
+++ linux-5.7.1-gentoo-2/arch/x86/Makefile	2020-06-14 13:35:25.154871267 +0300
@@ -128,8 +128,11 @@
         cflags-$(CONFIG_MJAGUAR) += $(call cc-option,-march=btver2)
         cflags-$(CONFIG_MBULLDOZER) += $(call cc-option,-march=bdver1)
         cflags-$(CONFIG_MPILEDRIVER) += $(call cc-option,-march=bdver2)
+        cflags-$(CONFIG_MPILEDRIVER) += $(call cc-option,-mno-tbm)
         cflags-$(CONFIG_MSTEAMROLLER) += $(call cc-option,-march=bdver3)
+        cflags-$(CONFIG_MSTEAMROLLER) += $(call cc-option,-mno-tbm)
         cflags-$(CONFIG_MEXCAVATOR) += $(call cc-option,-march=bdver4)
+        cflags-$(CONFIG_MEXCAVATOR) += $(call cc-option,-mno-tbm)
         cflags-$(CONFIG_MZEN) += $(call cc-option,-march=znver1)
         cflags-$(CONFIG_MZEN2) += $(call cc-option,-march=znver2)
         cflags-$(CONFIG_MPSC) += $(call cc-option,-march=nocona)```

**Comment by graysky2** [comment]
THanks for this, @maxbritov 

Can you comment on the scope of this?  Does the above need to be applied only with gcc>10 and linux>=5.7?

**Comment by maxbritov** [comment]
> Can you comment on the scope of this? Does the above need to be applied only with gcc>10 and linux>=5.7?
On my config I hit into this issue on 5.7, but  Jakub Jelinek (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95671#c12) found similar bugreport from 2017 and kernel 4.14: https://bugs.gentoo.org/642924

**Comment by graysky2** [comment]
Interesting... that implies all gcc versions and all kernel versions I am currently supporting.

**Comment by maxbritov** [comment]
TBM is only bdver{2,3,4} feature, not supported all other cpu.
-march-native will stiil fails on that cpus.
