### ISSUE TITLE
Kernel > 5.8

### ISSUE THREAD

**Issue by EduFrazao** [graysky2/kernel_gcc_patch#60]
New kernels will be supported? 5.9/10/11 ?
Thanks!

**Comment by graysky2** [comment]
Which kernels are you finding unsupported?

**Comment by EduFrazao** [comment]
> Which kernels are you finding unsupported?
Hi @graysky2 , thanks for answer.
I can't find a patch file to enable Zen2 CPU type on Kernel 5.11. I'm running gcc 9.3 here.

Some of avaliable patch files can be used in this version?

**Comment by graysky2** [comment]
I haven't backported for that old version of gcc

**Comment by EduFrazao** [comment]
As far I know, -march=zen2 is supported since GCC 9.1. I use it here, to compile other sources.

Unfortunatelly, 9.3 is the newest GCC supported with "stable" profiles on Gentoo. 10.2 is not marked as stable yet.

**Comment by graysky2** [comment]
OK... if it's supported then I would need to update the patch to use it.  I don't have tons of free time these days.  PRs are welcome particularly for backports like this.  Further, I don't have access to GCC 9.3 to test the code.

**Comment by EduFrazao** [comment]
Yes, GCC 10 is supported, but not released as stable for ~amd64 yet. As I use this machine for work, I run everything stable here ( except the kernel :) )
