### ISSUE TITLE
Add some explanation on Do NOT use 'native' when building for AMD chips!  Intel ONLY!

### ISSUE THREAD

**Issue by montjoie** [graysky2/kernel_gcc_patch#63]
On the patch commit log, the sentence:
Do NOT use 'native' when building for AMD chips!  Intel ONLY!
has no explanation.

Please tell why.

**Comment by graysky2** [comment]
I need to dig deeper, but I think it will be difficult to assign a native CPU out of some configs.  For example, `X86_INTEL_USERCOPY` config. I do that now but no other AMD chips are listed by upstream[1].

Further, I believe AMD chips should not be in the `X86_P6_NOP` config[2] or `X86_CMOV` config[3].

1. https://github.com/graysky2/kernel_gcc_patch/blob/master/enable_additional_cpu_optimizations_for_gcc_v10.1%2B_kernel_v5.8%2B.patch#L407

2. https://github.com/graysky2/kernel_gcc_patch/blob/master/enable_additional_cpu_optimizations_for_gcc_v10.1%2B_kernel_v5.8%2B.patch#L421

3. https://github.com/graysky2/kernel_gcc_patch/blob/master/enable_additional_cpu_optimizations_for_gcc_v10.1%2B_kernel_v5.8%2B.patch#L438

**Comment by montjoie** [comment]
I understand. Solution is to have INTEL_NATIVE and AMD_NATIVE.
Both which can select proper other CONFIGS. (INTEL_NATIVE selecting X86_INTEL_USERCOPY and X86_P6_NOP).
It remains the CMOV problem:
For example, my ryzen has the flag, but the CONFIG is for compiler generating cmov.
perhaps a simple bash script could test it.

**Comment by graysky2** [comment]
Good idea, PRs are welcomed.

**Comment by montjoie** [comment]
While looking for CMOV, I just saw that it has already "depends on x86_64" so adding new CONFIGs is useless UNLESS we care about 32 bits.
Same problem at least for TSC and X86_CMPXCHG64.

If you do not care about 32 bits, It will clean a lot the patch.

**Comment by graysky2** [comment]
@montjoie - Please share comments and insight here: https://github.com/graysky2/kernel_gcc_patch/pull/66

**Comment by graysky2** [comment]
This has been fixed with #67
