### ISSUE TITLE
Fail seeing level your hardware supports

### ISSUE THREAD

**Issue by montjoie** [graysky2/kernel_gcc_patch#64]
The patch said:
To see which level your hardware supports run:                                                      
  /lib/ld-linux-x86-64.so.2 --help | grep supported      

but if I run this I got:
/lib64/ld-linux-x86-64.so.2 --help
Usage: ld.so [OPTION]... EXECUTABLE-FILE [ARGS-FOR-PROGRAM...]
[...more help...]

Tested this on a gentoo, ubuntu and a debian

**Comment by FireBurn** [comment]
On gentoo:

/lib64/ld-linux-x86-64.so.2 --help | grep supported
  x86-64-v3 (supported, searched)
  x86-64-v2 (supported, searched)
  haswell (AT_PLATFORM; supported, searched)
  tls (supported, searched)
  x86_64 (supported, searched)

**Comment by FireBurn** [comment]
And the 32bit version:

/lib/ld-linux.so.2 --help | grep supported
  i686 (AT_PLATFORM; supported, searched)
  tls (supported, searched)
  sse2 (supported, searched)

**Comment by montjoie** [comment]
could you give your glibc version ?

```
equery b /lib64/ld-linux-x86-64.so.2
 * Searching for /lib64/ld-linux-x86-64.so.2 ... 
sys-libs/glibc-2.32-r7 (/lib64/ld-2.32.so)
sys-libs/glibc-2.32-r7 (/lib64/ld-linux-x86-64.so.2 -> ld-2.32.so)
```

**Comment by FireBurn** [comment]
glibc 2.33, if you're using Gentoo I wouldn't recommend unmasking this just yet

**Comment by montjoie** [comment]
I have compiled it and ran /var/tmp/portage/sys-libs/glibc-2.33/work/build-amd64-x86_64-pc-linux-gnu-nptl/elf/ld-linux-x86-64.so.2 and it prints now the necessary stuff.

So adding a hint that glibc >= 2.33 is mandatory for this test is necessary.

**Comment by sirlucjan** [comment]
Arch Linux:

```
$ /lib64/ld-linux-x86-64.so.2 --help | grep supported
  x86-64-v3 (supported, searched)
  x86-64-v2 (supported, searched)
  haswell (AT_PLATFORM; supported, searched)
  tls (supported, searched)
  x86_64 (supported, searched)
```
```
$ pacman -Qs glibc
local/glibc 2.33-4
    GNU C Library
$ pacman -Qs gcc
local/gcc 10.2.0-6 (base-devel)
    The GNU Compiler Collection - C and C++ frontends
local/gcc-libs 10.2.0-6
    Runtime libraries shipped by GCC
$ pacman -Qs binutils
local/binutils 2.36.1-2 (base-devel)
    A set of programs to assemble and manipulate binary and object files
```

**Comment by graysky2** [comment]
Thanks for opening.  I added more direct wording to the comment block.
