### ISSUE TITLE
PinePhone CPU Allwinner A64 profile

### ISSUE THREAD

**Issue by VildaTech** [graysky2/kernel_gcc_patch#71]
The PinePhone is open source Linux phone with weak CPU, but i think compilation flags and profiles can push him to a little bit and make phone more usable.
I saw there are some patches for RPi4 and ARM Cortex-A72, so i wish there is a something for ARM Allwinner A64.

PinePhone 
https://www.pine64.org/pinephone/

PinePhone SoC Wiki + some documentation
https://linux-sunxi.org/A64

My first thought: Allwinner A64 have very small cache memory 512KiB L2-Cache 32KiB (Instruction) / 32KiB (Data) L1-Cache per core.
Compilation with -Os (lower memory usage) can be better choice and bring a little bit more performance than -O3, because cache memory is very small. I believe you know best what is the best choice for this weak CPU.

Thank you!

**Comment by graysky2** [comment]
The RPi4 patch was an experiment.  As you see from the comments on the commit, it offers no real world benefit vs vanilla flags for the kernel.
