### ISSUE TITLE
gcc 11 and subarch selection

### ISSUE THREAD

**Issue by barmadrid** [graysky2/kernel_gcc_patch#72]
Building `linux-ck` with `gcc 11` (currently in official Arch testing repo).

I have set `_subarch=33` (for Intel) in PKGBUILD, however with gcc 11 we introduced more subarchs so the manual selection in PKGBUILD ends up being wrong (MSAPPHIRERAPIDS in my case).

**Comment by graysky2** [comment]
Yes, this is to be expected as the new options will appear as a function of which gcc is on your system.  I will update the comments in the PKGBUILD once gcc 11 is transititioned into [core].
